GlyphConversion = {}

--Creates the tables where the glyph conversions are stored for each type
GlyphConversion.MW = {}
GlyphConversion.PG = {}
GlyphConversion.UN = {}

GlyphConversion.MW["q"] = "Point of Origin"
GlyphConversion.MW["w"] = "Crater"
GlyphConversion.MW["e"] = "Virgo"
GlyphConversion.MW["r"] = "Bootes"
GlyphConversion.MW["t"] = "Centaurus"
GlyphConversion.MW["y"] = "Libra"
GlyphConversion.MW["u"] = "Serpens Caput"
GlyphConversion.MW["i"] = "Norma"
GlyphConversion.MW["o"] = "Scorpius"
GlyphConversion.MW["p"] = "Corona Australis"
GlyphConversion.MW["["] = "Scutum"
GlyphConversion.MW["]"] = "Sagittarius"
GlyphConversion.MW["\\"] = "Aquila"
GlyphConversion.MW["a"] = "Microscopium"
GlyphConversion.MW["s"] = "Capricornus"
GlyphConversion.MW["d"] = "Piscis Austrinus"
GlyphConversion.MW["f"] = "Equuleus"
GlyphConversion.MW["g"] = "Aquarius"
GlyphConversion.MW["h"] = "Pegasus"
GlyphConversion.MW["j"] = "Sculptor"
GlyphConversion.MW["k"] = "Pisces"
GlyphConversion.MW["l"] = "Andromeda"
GlyphConversion.MW[";"] = "Triangulum"
GlyphConversion.MW["'"] = "Aries"
GlyphConversion.MW["z"] = "Perseus"
GlyphConversion.MW["x"] = "Cetus"
GlyphConversion.MW["c"] = "Taurus"
GlyphConversion.MW["v"] = "Auriga"
GlyphConversion.MW["b"] = "Eridanus"
GlyphConversion.MW["n"] = "Orion"
GlyphConversion.MW["m"] = "Canis Minor"
GlyphConversion.MW[","] = "Monoceros"
GlyphConversion.MW["."] = "Gemini"
GlyphConversion.MW["/"] = "Hydra"
GlyphConversion.MW["1"] = "Lynx"
GlyphConversion.MW["2"] = "Cancer"
GlyphConversion.MW["3"] = "Sextans"
GlyphConversion.MW["4"] = "Leo Minor"
GlyphConversion.MW["5"] = "Leo"

GlyphConversion.PG["q"] = "Subido"
GlyphConversion.PG["w"] = "Aaxel"
GlyphConversion.PG["e"] = "Abrin"
GlyphConversion.PG["r"] = "Acjesis"
GlyphConversion.PG["t"] = "Aldeni"
GlyphConversion.PG["y"] = "Alura"
GlyphConversion.PG["u"] = "Amiwill"
GlyphConversion.PG["i"] = "Arami"
GlyphConversion.PG["o"] = "Avoniv"
GlyphConversion.PG["p"] = "Baselai"
GlyphConversion.PG["["] = "Bydo"
GlyphConversion.PG["]"] = "Ca Po"
GlyphConversion.PG["\\"] = "Danami"
GlyphConversion.PG["a"] = "Dawnre"
GlyphConversion.PG["s"] = "Ecrumig"
GlyphConversion.PG["d"] = "Elenami"
GlyphConversion.PG["f"] = "Gilltin"
GlyphConversion.PG["g"] = "Hacemill"
GlyphConversion.PG["h"] = "Hamlinto"
GlyphConversion.PG["j"] = "Illume"
GlyphConversion.PG["k"] = "Laylox"
GlyphConversion.PG["l"] = "Lenchan"
GlyphConversion.PG[";"] = "Olavii"
GlyphConversion.PG["'"] = "Once el"
GlyphConversion.PG["z"] = "Poco re"
GlyphConversion.PG["x"] = "Ramnon"
GlyphConversion.PG["c"] = "Recktic"
GlyphConversion.PG["v"] = "Robandus"
GlyphConversion.PG["b"] = "Roehi"
GlyphConversion.PG["n"] = "Salma"
GlyphConversion.PG["m"] = "Sandovi"
GlyphConversion.PG[","] = "Setas"
GlyphConversion.PG["."] = "Sibbron"
GlyphConversion.PG["/"] = "Tahnan"
GlyphConversion.PG["1"] = "Zamilloz"
GlyphConversion.PG["2"] = "Zeo"

GlyphConversion.UN["q"] = 17
GlyphConversion.UN["w"] = 1
GlyphConversion.UN["e"] = 2
GlyphConversion.UN["r"] = 3
GlyphConversion.UN["t"] = 4
GlyphConversion.UN["y"] = 5
GlyphConversion.UN["u"] = 6
GlyphConversion.UN["i"] = 7
GlyphConversion.UN["o"] = 8
GlyphConversion.UN["p"] = 9
GlyphConversion.UN["["] = 10
GlyphConversion.UN["]"] = 11
GlyphConversion.UN["\\"] = 12
GlyphConversion.UN["a"] = 13
GlyphConversion.UN["s"] = 14
GlyphConversion.UN["d"] = 15
GlyphConversion.UN["f"] = 16
GlyphConversion.UN["g"] = 18
GlyphConversion.UN["h"] = 19
GlyphConversion.UN["j"] = 20
GlyphConversion.UN["k"] = 21
GlyphConversion.UN["l"] = 22
GlyphConversion.UN[";"] = 23
GlyphConversion.UN["'"] = 24
GlyphConversion.UN["z"] = 25
GlyphConversion.UN["x"] = 26
GlyphConversion.UN["c"] = 27
GlyphConversion.UN["v"] = 28
GlyphConversion.UN["b"] = 29
GlyphConversion.UN["n"] = 30
GlyphConversion.UN["m"] = 31
GlyphConversion.UN[","] = 32
GlyphConversion.UN["."] = 33
GlyphConversion.UN["/"] = 34
GlyphConversion.UN["1"] = 35
GlyphConversion.UN["2"] = 36

return GlyphConversion